apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kennedn-github-io
spec:
  ingressClassName: public
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kennedn-github-io
            port:
              number: 80
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: livestats
            port:
              number: 5000

